name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on:
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
      - name: Generate the static website
        run: npx antora site.yml --stacktrace --pull
      - name: Deploy to Github Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v2.10.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_PAT }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build/site
